apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: hello-world
  labels:
    app.kubernetes.io/name: hello-printer
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hello-printer
  ports:
    - name: http
      port: 80
      targetPort: http
